server:
  port: 8083
  address: 127.0.0.1

#线程池配置
yf:
  thread-pool:
    pool:
      enabled: true
      coreNums: 10    #线程池核心线程数
      maxNums: 50    #线程池最大线程数
      poolName: yf-thread-pool   #线程池名称
      threadName: yf-thread      #线程名称
      isDaemon: true      #是否是守护线程
      coreDestroy: false  #核心线程是否销毁
      aliveTime: 5000        #线程存活时间（单位：ms）
      rejectStrategyName: discard   #拒绝策略名称
    queue:     #(由于queue比较重要，所以与pool和monitor一个层级)
      partitioning: false  #是否分区化(如果是false，只需要读取capacity和queueName)
      partitionNum: 10      #分区数量
      capacity: 10000         #队列容量（不写代表null，为无界）
      queueName: linked     #队列名称
      offerPolicy: ROUND_ROBIN       #入队策略
      pollPolicy: THREAD_BINDING      #出队策略
      removePolicy: ROUND_ROBIN     #移除策略
    monitor:
      enabled: true       #是否开启监控
      fixedDelay: 1000    #后台像前端推送线程状态信息的间隔时间(单位：ms)
    service-registry:      #是否开启服务注册
        enabled: false
        heartBeat: 10000   #心跳间隔时间(单位：ms)
        expireTime: 12000  #注册数据失效时间(单位：ms)


#redis配置
spring:
  data:
    redis:
      # Redis服务器地址
      host: localhost
      # Redis服务器端口
      port: 6379
      # Redis服务器密码（如果没有密码则省略）
      password:
      # 数据库索引，默认为0
      database: 0
      # 连接超时时间（毫秒）
      timeout: 10000ms
      # 连接池配置
      lettuce:
        pool:
          # 最大连接数，默认8
          max-active: 8
          # 最大阻塞等待时间，默认-1
          max-wait: -1ms
         # 最大空闲连接，默认8
          max-idle: 8
          # 最小空闲连接，默认0
          min-idle: 0




