server:
  port: 8081
  address: 127.0.0.1

#线程池配置
yf:
  thread-pool:
    little-chief:            #GCTaskManager中的线程池（用来做异步任务或者一些补救措施等等）
      enabled: true
      useVirtualThread: false #是否使用虚拟线程
      coreNums: 10    #线程池核心线程数
      maxNums: 50    #线程池最大线程数
      threadName: yf-thread      #线程名称
      useDaemon: true      #是否是守护线程
      aliveTime: 5000        #线程存活时间（单位：ms）
      rejectStrategyName: discard   #拒绝策略名称
    queue:
      partitioning: true  #是否分区化(如果是false，只需要读取capacity和queueName)
      partitionNum: 10      #分区数量
      capacity: 10000         #队列容量（不写代表null，为无界）
      queueName: linked     #队列名称
      offerPolicy: round_robin       #入队策略
      pollPolicy: thread_binding      #出队策略
      removePolicy: round_robin     #移除策略
    monitor:
      enabled: true       #是否开启监控
      fixedDelay: 1000    #后台像前端推送线程状态信息的间隔时间(单位：ms)
    service-registry:      #是否开启服务注册
        enabled: false
        heartBeat: 10000   #心跳间隔时间(单位：ms)
        expireTime: 12000  #注册数据失效时间(单位：ms)


#redis配置
spring:
  data:
    redis:
      # Redis服务器地址
      host: localhost
      # Redis服务器端口
      port: 6379
      # Redis服务器密码（如果没有密码则省略）
      password:
      # 数据库索引，默认为0
      database: 0
      # 连接超时时间（毫秒）
      timeout: 10000ms
      # 连接池配置
      lettuce:
        pool:
          # 最大连接数，默认8
          max-active: 8
          # 最大阻塞等待时间，默认-1
          max-wait: -1ms
         # 最大空闲连接，默认8
          max-idle: 8
          # 最小空闲连接，默认0
          min-idle: 0




