fy:
  thread-pool:
    enabled: true
    coreNums: 5
    maxNums: 10
    poolName: yf-thread-pool
    threadName: yf-thread
    isDaemon: true
    coreDestroy: false
    aliveTime: 5
    queueName: linked
    queueCapacity:
    rejectStrategyName: callerRuns
    monitor:
      enabled: true
      fixedDelay: 1000
      qReplaceable: true  #默认是开启的（不写这个key默认开启，写了后只有value为true才是开启，以下同理）
      rsReplaceable: true
server:
  port: 8080
