fy:
  thread-pool:
    enabled: true
    coreNums: 5
    maxNums: 10
    poolName: yf-thread-pool
    threadName: yf-thread
    isDaemon: true
    coreDestroy: false
    aliveTime: 5
    queueName: linked
    queueCapacity:
    rejectStrategyName: mys
    monitor:
      enabled: true
